# -*- coding: utf-8 -*-
"""RohitCombination.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FUbmqVoBSM_12AWhZwbu2x3MUC_NDQR-
"""

PT=[45,50,60] #Enter Values or Precursor Temperature
WT=[30,50,75] #Wafer Temperature
PPT=[0.5,1.0,2.0] #Precursor Pulse Time

#
List=[(a,b,c) for a in PT for b in WT for c in PPT]
List



